### ISSUE TITLE
UnhandledRejection error When proxy failed?

### ISSUE THREAD

**Issue by kingbotss** [szmarczak/http2-wrapper#66] opened 2021-03-22 16:31 UTC
I am getting undhandledrejection error when proxy socket connect to failed.
proxy is http
and protocol is http2

I am getting this type of errors when proxy is failed.
with request it is only showing error like proxy socket failed. but with http2-wrapper I can't solve this issue.

**Comment by szmarczak** [comment] 2021-03-23 09:12
I don't know how to reproduce this.

**Comment by kingbotss** [comment] 2021-03-28 15:25
I can't share full code, but 
I am using got library. I think it uses your library for http2 connections. 
I am passing a proxy to got.

When proxy is failed(actually proxy not working) it should say tunnel error or something like that, but it stopping my next code.

**Comment by szmarczak** [comment] 2021-03-28 21:20
Unfortunately I cannot help with this information. It's not enough to reproduce anything.

**Comment by mnmkng** [comment] 2021-04-13 09:18
@szmarczak would this stack trace help?

```
(node:12200) UnhandledPromiseRejectionWarning: Error: The proxy server rejected the request with status code 502
    at Http2OverHttp.createConnection (G:\...\node_modules\http2-wrapper\source\proxies\h2-over-hx.js:19:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async entry (G:\...\node_modules\http2-wrapper\source\agent.js:395:15)
(node:12200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Comment by szmarczak** [comment] 2021-04-13 09:33
@mnmkng Not so much. What is your `http2-wrapper` version?

**Comment by mnmkng** [comment] 2021-04-13 09:47
@szmarczak we're using latest. I wonder if it could be caused by the fact that we're using the proxy agents directly from `http2.proxies`. Do we need to add some extra error handling? https://github.com/apify/got-scraping/blob/0f0be67ae003d58451ab4cd7010f451712120941/src/handlers/proxy.js#L48

**Comment by szmarczak** [comment] 2021-04-13 14:43
> Do we need to add some extra error handling?

All you need is `try/await got/catch` or `got(...).catch()` - that should be enough. You can try attaching a `beforeError` hook and see if the error is being passed to Got.

**Comment by mnmkng** [comment] 2021-04-13 16:42
We do catch the errors from `got`, we're not crazy :) We're making tens of thousands of requests a minute and some of them fail for various reasons. Yet only this particular error crashed the process. The `beforeError` is an interesting tip. We'll try that to narrow the problem down. Thanks.

**Comment by mnmkng** [comment] 2021-06-02 20:44
Still trying to figure out what this is. I cant reproduce it locally, but in our production runs (tens of thousands of requests) it happens quite frequently. It seems that not only errors like the one above, but pretty much any error on the proxy level can produce an unhandled rejection. We're seeing 502 errors, socket hangups and even stuff like 
![image](https://user-images.githubusercontent.com/23726914/120547905-0054ee00-c3f2-11eb-91f8-cf2d57bffab3.png)

Some notes:

- in our wrapper of `got`, we use latest http2-wrapper
- we wrap `got@11.8.2` which internally uses `http2-wrapper@1.0.3`
- I have a hunch that this could be a problem, but can't confirm it.
- The error in the screenshot above is actually emitted from the 1.0.3 version `got` installs, not from our own implementation. This suggests a problem in `got` or the old version of `http2-wrapper`.
- we can't downgrade to 1.0.3 (to try to match the versions) because we need the `proxies` agents introduced in 2.0
- I tried installing `got@main` which uses 2.0.5 but it won't build for me due to TS errors (same in `got` CI)
- I also tried moving 2.0.5 to top level in `node_modules` to force `got` to use it, but ended up with this error https://github.com/sindresorhus/got/issues/1659#issuecomment-805419941

I'm a bit lost here, so would appreciate any idea you might have how to debug this. Thanks!

**Comment by mnmkng** [comment] 2021-06-02 20:49
In this screenshot you can see the mixed up `http2-wrapper` versions. One path points to `node_modules/http2-wrapper` and other points to `node_modules/got-scraping/node_modules/http2-wrapper`. Not sure if it's helpful, but maybe it better illustrates what I was trying to say above.

![image](https://user-images.githubusercontent.com/23726914/120550117-bde0e080-c3f4-11eb-97dd-063c532421f3.png)

**Comment by szmarczak** [comment] 2021-06-02 21:46
@mnmkng I'm pretty sure it's because of the old version of `http2-wrapper`. Got v12 is going to have v2 of `http2-wrapper`, which is a lot more stable. The only thing Got v12 is missing is docs, which need to be rewritten because of so many changes. Currently I'm a bit short on time as I'm constantly dealing with uni stuff. I'll let you know when Got v12 is released.

It seems that `got-scraping` is running `http2-wrapper` v1 with agents from v2, which may be incompatible. They should make sure to run `http2-wrapper` v2 in the following way:

[here](https://github.com/apify/got-scraping/blob/0f0be67ae003d58451ab4cd7010f451712120941/src/index.js#L18)

```js
const http2 = require('http2-wrapper');

...
	request: http2.auto,
	mutableDefaults: true,
...
```

**Comment by szmarczak** [comment] 2021-06-02 21:47
> I tried installing got@main which uses 2.0.5 but it won't build for me due to TS errors (same in got CI)

Unfortunately this is caused by upstream. I'll fix this manually in an hour and will let you know.

**Comment by szmarczak** [comment] 2021-06-02 21:51
@mnmkng That SSL error means a lot. I don't think we're testing this, so this is possibly a new test case :)

**Comment by szmarczak** [comment] 2021-06-02 22:53
@mnmkng You can try builiding `got#main` now. Fixed linting and the build passes here.

**Comment by mnmkng** [comment] 2021-06-03 17:00
@szmarczak Tried installing it now, but it comes as an already built ES module, so I can't `require` it. Would have to rewrite our library to an ES module too. And then the next library that uses this library ...

Do you plan shipping Got 12 with CJS exports or are you going all-in ESM? I [read this](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1) and it's a bit scary.

```
node:internal/modules/cjs/loader:1109
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/mnmkng/Projects/Apify/got-scraping/node_modules/got/dist/source/index.js
require() of ES modules is not supported.
require() of /Users/mnmkng/Projects/Apify/got-scraping/node_modules/got/dist/source/index.js from /Users/mnmkng/Projects/Apify/got-scraping/src/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/mnmkng/Projects/Apify/got-scraping/node_modules/got/dist/source/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/mnmkng/Projects/Apify/got-scraping/node_modules/got/package.json.

```

**Comment by szmarczak** [comment] 2021-06-03 17:40
@mnmkng You can't `require` it, but you can `await import` it :)

All-in ESM. See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by mnmkng** [comment] 2021-06-03 17:53
@szmarczak Yeah, but then I would have to export a Promise from `got-scraping`, which is probably an even worse idea than just migrating to ESM. In any case, I would have to rewrite all libs that use `got-scraping` as a dependency too, to accept the new API. And then rewrite all the code that imports this other lib...

We have hundreds of projects and this would snowball fast. The good thing about encapsulation is that a breaking change in a dependency doesn't have to be a breaking change in the module that uses it. You can typically update some private functions to handle the breaking change and live happily ever after. But this ESM stuff, unless I understand it wrongly, is a megabreaking change, because it will bubble up all the way from the smallest sub dependency all the way to your project and you can't do anything about it.

Or can you?

**Comment by szmarczak** [comment] 2021-06-03 18:31
https://runkit.com/szmarczak/60b91819998045001b70aa18 A drawback to this is that you can't use `instance.stream` and `instance.defaults` until you make a first Promise request (but you can use promise shortcuts though).

**Comment by szmarczak** [comment] 2021-06-03 18:44
> I guess I can always add a build step and export both CJS and ESM and somehow make it work. 

It should be possible. Alternatively you can clone the Got repo and force it to export CJS.

**Comment by mnmkng** [comment] 2021-06-16 16:41
Hi @szmarczak, so I'm quite deep into the rewrite to got 12 ([using got-cjs](https://github.com/apify/got-cjs)) now and found one thing in `http2-wrapper` code that causes:

```
Error: Cannot call end after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call end after a stream was destroyed
    at new NodeError (node:internal/errors:363:5)
    at errorBuffer (node:internal/streams/writable:522:26)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I believe it could be related to [your comment in `got`](https://github.com/sindresorhus/got/issues/1659#issuecomment-805419941).

I was not able to pinpoint the problem exactly. I think it has something to do with our extra layer of caching. We needed to add it because the internal `auto` resolution was not working well for us in some combinations of proxy usage. I think it was in making HTTP2 requests over an HTTP proxy, but I'm not sure exactly. @petrpatek could know more.

Anyway, drilling down into the problem, I found that if I change this:

https://github.com/szmarczak/http2-wrapper/blob/117e112d68ce4a583b1578c69a65deea8b2ec224/source/agent.js#L388-L393
to this:

```js
const computedOptions = {
    ...options,
    createConnection: this.createConnection,
    settings: this.settings,
    session: this.tlsSessionCache.get(name),
};
```

The error goes away and our test passes. It's because the `options` include a `createConnection` property that is `undefined` and therefore overwrites the previously set `this.createConnection` function. This causes 

https://github.com/szmarczak/http2-wrapper/blob/117e112d68ce4a583b1578c69a65deea8b2ec224/source/agent.js#L396

to fail with:

```
TypeError: Cannot read property 'call' of undefined
    at entry (/Users/mnmkng/Projects/Apify/got-scraping/node_modules/http2-wrapper/source/agent.js:398:54)
    at Agent._processQueue (/Users/mnmkng/Projects/Apify/got-scraping/node_modules/http2-wrapper/source/agent.js:223:6)
    at /Users/mnmkng/Projects/Apify/got-scraping/node_modules/http2-wrapper/source/agent.js:656:9
    at new Promise (<anonymous>)
    at Agent.getSession (/Users/mnmkng/Projects/Apify/got-scraping/node_modules/http2-wrapper/source/agent.js:253:10)
    at /Users/mnmkng/Projects/Apify/got-scraping/node_modules/http2-wrapper/source/agent.js:662:9
    at new Promise (<anonymous>)
    at Agent.request (/Users/mnmkng/Projects/Apify/got-scraping/node_modules/http2-wrapper/source/agent.js:661:10)
    at ClientRequest.flushHeaders (/Users/mnmkng/Projects/Apify/got-scraping/node_modules/http2-wrapper/source/client-request.js:428:32)
    at ClientRequest._final (/Users/mnmkng/Projects/Apify/got-scraping/node_modules/http2-wrapper/source/client-request.js:207:8)
```

But this error is swallowed somewhere and can be read if you break execution at https://github.com/szmarczak/http2-wrapper/blob/117e112d68ce4a583b1578c69a65deea8b2ec224/source/agent.js#L643

So in the end, it fails with the `Cannot call end after a stream was destroyed` error above.

**Comment by szmarczak** [comment] 2021-06-16 17:22
Thank you for the details! This helps a lot! I will look into this ASAP. This week and the next one I'm dealing with exam session at my uni (the end of the first year). I'll try to fix this in the next few days though.

**Comment by mnmkng** [comment] 2021-06-16 19:11
Thanks! I'm not sure if it will fix the original problem, but it is a step in the right direction I hope.

**Comment by mnmkng** [comment] 2021-06-17 15:22
@szmarczak I have a hunch I might have found an issue in our code that could've been causing weird behavior, but could you help me a bit please with understanding asynchronous handlers in `got`? Especially in `got` 12. In the docs, there is this:

**Note:** Handlers can be asynchronous. The recommended approach is:

```js
const handler = (options, next) => {
	if (options.isStream) {
		// It's a Stream
		return next(options);
	}

	// It's a Promise
	return (async () => {
		try {
			const response = await next(options);
			response.yourOwnProperty = true;
			return response;
		} catch (error) {
			// Every error will be replaced by this one.
			// Before you receive any error here,
			// it will be passed to the `beforeError` hooks first.
			// Note: this one won't be passed to `beforeError` hook. It's final.
			throw new Error('Your very own error.');
		}
	})();
};

const instance = got.extend({handlers: [handler]});
```

So can they be `async` functions or not? In our code, we have this handler:

https://github.com/apify/got-scraping/blob/2badb20fabc61a3d6b96ee8546a7a6fe375d1837/src/handlers/alpn.js#L8-L25

I'm debugging a failing test and I found that it does not wait for the handler to fully execute. The execution goes deep into the ALPN handling and then jumps directly into making the HTTP request (calling `makeRequest` in `got`), without executing other handlers in the chain. Only after that are the remaining handlers executed.

I assume it has something to do with timing or Promises not being correctly awaited in got, but at the same time I'm not sure if we're using the handlers correctly. Other handlers don't seem to have this problem, even though they are also `async` functions. The difference between other handlers and this one is that only this one actually does some "long" async task.

I'd be glad for any ideas. Thanks!

**Comment by szmarczak** [comment] 2021-06-17 15:31
> So can they be async functions or not?

They can return a Promise only if `options.isStream` is `false`. If it's `true` then you need to return a Stream.

**Comment by mnmkng** [comment] 2021-06-17 15:38
Ok, then there must be something wrong in `got` 12, because we're not using streams in this case. I'll try to find out what.

**Comment by szmarczak** [comment] 2021-06-17 17:04
@mnmkng Also please note that the docs for Got v12 haven't been updated yet. WIP.

**Comment by mnmkng** [comment] 2021-06-17 17:05
I know. I was able to find a reproduction case for the bug. Will post to got repo soon.

**Comment by mnmkng** [comment] 2021-06-17 20:44
cc the got issue here for reference https://github.com/sindresorhus/got/issues/1760

**Comment by mnmkng** [comment] 2021-06-21 08:09
@szmarczak I hope I'm not bothering you too much during finals. I think I'm quite sure now that even though I found some issues in `http2-wrapper` and `got` in this process, the original issue of the unhandled rejections is caused by the fact that we don't handle streams properly. As you said above, handlers should always return a stream when `isStream` is `true`, but we do not respect that and in some handlers we always return a `Promise`.

Is there any recommended way to execute async handlers before the request stream is dispatched in `got`? Maybe a callback we could call in the last handler to tell `got` "you can `request.end()` now" ? We need streams for memory management, but at the same time we need async handlers for ALPN and proxy server ALPN.

**Comment by szmarczak** [comment] 2021-06-21 08:25
> I hope I'm not bothering you too much during finals.

It's okay, no problem :)

> Is there any recommended way to execute async handlers before the request stream is dispatched in got?

It's not possible to execute an async handler. But you can run an async function in a `beforeRequest` hook.

> at the same time we need async handlers for ALPN and proxy server ALPN.

Maybe you need to use the `request` function instead. The `request` function can be an async function.

> Maybe a callback we could call in the last handler to tell got "you can request.end() now"?

Yes, internally there's `request.flush()` but it's automatically executed by Got when all handlers finish. We could expose a `_detach` option - if it's `true` then don't flush the request automatically.

**Comment by mnmkng** [comment] 2021-06-24 08:31
Hey @szmarczak, I hope your finals are progressing well 🤞 I rewrote our library from handlers to hooks and shuffled some things around and it seems to have fixed the unhandled rejections problem.

However, we're getting a lot of `Cannot call end after a stream was destroyed` errors now. They are correctly handled and retried, so not a huge problem. We're using `got` 11 and `http2-wrapper` 2.0.5 and I think those errors are caused by `http2-wrapper`.

Earlier I reported that `...options` problem overwriting `createConnection` and assumed it was related to this `got` issue: https://github.com/sindresorhus/got/issues/1659#issuecomment-805419941 , but after some more testing I found that the `connection: keep-alive` problem happens even if I swap the order of `...options` so it's something unrelated. I was able to break execution at an exception where internal Node.js code complained that  `connection` is not a valid HTTP2 header, but the error thrown from `got` was again `Cannot call end after a stream was destroyed`. I'm pretty sure it was some `http2-wrapper` code that produced this error.

Anyway, just wanted to drop it here for further reference. I'll try to come up with exact reproduction cases for both errors. And thank you very much for the support.

By the way, since we're in Prague (Apify, the company I build this stuff for) and you're in Poland, would you be interested in a summer internship or remote work on our open-source technologies? Paid, of course. We'd be happy to have you.

**Comment by szmarczak** [comment] 2021-06-24 13:09
> I hope your finals are progressing well 🤞

Yup, only three exams left and the first year will be over.

Thanks for the detailed breakthrough. Where does the `connection` header come from? Indeed, `connection` is not a valid HTTP/2 header. Perhaps we could just ignore it.

I may know what's going on with the `Cannot call end after a stream was destroyed` error. `http2-wrapper` `ClientRequest` instance may throw before calling `request.end()`. I'll check this.

> By the way, since we're in Prague (Apify, the company I build this stuff for) and you're in Poland, would you be interested in a summer internship or remote work on our open-source technologies? Paid, of course. We'd be happy to have you.

Let's discuss this over email.

**Comment by mnmkng** [comment] 2021-06-26 09:34
> Thanks for the detailed breakthrough. Where does the connection header come from? Indeed, connection is not a valid HTTP/2 header. Perhaps we could just ignore it.

Yeah, I know. It was a bug in our code created in the middle of my refactoring. But it was quite difficult to debug, because the real error was obscured by `Cannot call end...`.

I'm sorry I might have confused you with the `connection: keep-alive`. I merely wanted to say that: "`Cannot call end...` errors will not be fixed merely by swapping the `...options`" as I suggested earlier.

**Comment by szmarczak** [comment] 2021-06-26 12:28
I'm sorry the errors are confusing. 

The `connection: keep-alive` is quite common, so I think we could just remove it automatically if present and throw only when it's any other value.

**Comment by mnmkng** [comment] 2021-06-28 09:43
Found a very simple way to reproduce the `Cannot call end...` error. It seems that it obscures pretty much any error.

```js
import got from 'got';
import http2 from 'http2-wrapper';

const response = await got({
    url: 'https://example.com',
    timeout: 1,
    request: http2.auto, // comment this out and the error is thrown correctly
});

console.dir(response);
``` 

And yeah, I agree that silently removing `connection: keep-alive` from HTTP2 headers is probably the best solution. Sometimes it creeps in, who knows from where.

**Comment by szmarczak** [comment] 2021-07-11 18:47
This looks like a Node.js bug:

https://github.com/sindresorhus/got/blob/c0b5346433996e761bca15cdb942f2b740264118/source/core/index.ts#L464

`this._request.destroyed` is `false` while it should be `true`

**Comment by szmarczak** [comment] 2021-07-11 19:50
The `Cannot call end` is a bug inside Got. I believe it's fixed in Got 12. So here's what happens:

1. `currentRequest` is `this` (Request - this is a Got stream instance) 
https://github.com/sindresorhus/got/blob/f896aa52abc41fe40d4942da94a0408477358f14/source/core/index.ts#L2226

2. `currentRequest.end()` 
https://github.com/sindresorhus/got/blob/f896aa52abc41fe40d4942da94a0408477358f14/source/core/index.ts#L2242

3. `_final` adds `currentRequest.end()` to the queue (yes, there's a loop that shouldn't be here)
https://github.com/sindresorhus/got/blob/f896aa52abc41fe40d4942da94a0408477358f14/source/core/index.ts#L2697

4. `currentRequest.destroy()` (via timeout)

5. `currentRequest.end()` throws

**Comment by szmarczak** [comment] 2021-07-11 19:59
I think there's a race condition in Node.js. Before 5. is executed there's a `request.destroyed` check which mistakenly returns `false`.

**Comment by szmarczak** [comment] 2021-07-11 20:43
So there are two errors coming from Node.js:

```js
const {Writable} = require('stream');

const s = new Writable({
    final() {}
});

const callback = error => {
    console.error(error);
};

// Remove `callback` and it works
s.end(callback);               // Error: Cannot call end after a stream was destroyed
s.destroy(new Error('oh no')); // Error: oh no
```

The behavior is really weird. If you destroy the stream but it's still pending, it depends if there's an end callback. If there is, then it will pass an error. If there's not, then there will be only one error.

**Comment by szmarczak** [comment] 2021-07-11 21:03
https://github.com/nodejs/node/issues/39356

**Comment by szmarczak** [comment] 2021-07-12 14:37
Included a workaround in Got: https://github.com/sindresorhus/got/commit/226cc3995f6e16938163ebde24d8762e7dcd15e2

**Comment by szmarczak** [comment] 2021-07-12 16:22
Ah yes, the unhandled rejection comes from this line in [`http2-wrapper@1.0.3`](https://cdn.jsdelivr.net/npm/http2-wrapper@1.0.3/source/agent.js):

```js
						createConnection: this.createConnection,
```

`http2.connect` expects a synchronous function, but this must be an async function because there is no `callback` like in the native `http` API. If you set the `request` option to `http2wrapper.auto` then the errors will be gone. `http2` still needs to be set to `true`.

**Comment by szmarczak** [comment] 2021-07-12 16:25
```js
const http2 = require('http2-wrapper');
const got = require('got');

const got2 = got.extend({
    request: http2.auto,
    http2: true
});

(async () => {
    const response = await got2('https://httpbin.org/anything');
    console.log(response.headers[':status']);
})();
```

**Comment by szmarczak** [comment] 2021-07-12 18:29
@mnmkng Replied to your email.

**Closed by szmarczak** 2021-07-12 18:29 UTC
